config/routes.rb
Rails.application.routes.draw do
  get 'price_analysis/get_price'
  get 'price_analysis/index'
  get 'piping_flanges/index'
  get 'inflasis/index'
  get 'faq/index'
  get 'jargas_instruments/index'
  get 'jargas_pipelines/index'
  get 'jargas_jasakonstruksis/index'
  get 'jasakonstruksi_rokankonstruksis/index'
  get 'jasakonstruksi_rokanelkons/index'
  get 'pipeline_spacels/index'
  get 'pipeline_fjcs/index'
  get 'pipeline_flanges/index'
  get 'pipeline_hot/index'
  get 'pipeline_valves/index'
  get 'pipeline_barreds/index'
  get 'pipeline_insulations/index'
  get 'pipeline_linepipes/index'
  get 'instrument_miscellaneouss/index'
  get 'instrument_icsss/index'
  get 'instrument_materings/index'
  get 'instrument_matering/index'
  get 'instrument_fires/index'
  get 'instrument_valves/index'
  get 'instrument_fields/index'
  get 'mechanicals/index'
  get 'elektrikals/index'
  get 'civiljasas/index'
  get 'civilmaterials/index'
  get 'pipingspitems/index'
  get 'pipingvalves/index'
  get 'pipingbolts/index'
  get 'pipingbolt/index'
  get 'pipinggasket/index'
  get 'gaskets/index'
  get 'pipingfitings/index'
  get 'pipingfiting/index'
  get 'pipingpipes/index'

  get 'dashboard/home_piping'
  get 'dashboard/home_pipeline'
  get 'dashboard/home_instrument'
  get 'dashboard/home_civil'
  get 'dashboard/home_jargas'
  
  resources :inflasis

  resources :faq do
    get :getDataTemplate, on: :collection
    member do
      end
    get :import, on: :collection
  end

  resources :products do
    get :new_modalbox, on: :collection
  end
  resources :types do
    get :new_modalbox, on: :collection
  end
  post 'import_items/create'

  post 'brochures/create'

  post 'brands/create'

  post 'vendors/create'

  post 'disiplines/create'

  put 'disiplines/update'

  post 'types/create'

  post 'products/create'

  post 'units/create'

  get 'jargas_instruments/new'
  get 'jargas_pipelines/new'
  get 'jargas_jasakonstruksis/new'
  get 'elektrikals/new'
  get 'mechanicals/new'
  get 'instrument_fields/new'
  get 'instrument_valves/new'
  get 'instrument_fires/new'
  get 'instrument_materings/new'
  get 'instrument_icsss/new'
  get 'instrument_miscellaneouss/new'
  get 'pipeline_linepipes/new'
  get 'pipeline_insulations/new'
  get 'pipeline_barreds/new'
  get 'pipeline_valves/new'
  get 'pipeline_hot/new'
  get 'pipeline_flanges/new'
  get 'pipeline_fjcs/new'
  get 'pipeline_spacels/new'
  get 'pipingpipes/new'
  get 'pipingfitings/new'
  get 'pipinggasket/new'
  get 'pipingbolts/new'
  get 'piping_flanges/new'
  get 'pipingvalves/new'
  get 'civilmaterials/new'
  get 'civiljasas/new'
  get 'pipingspitems/new'
  get 'jasakonstruksi_rokankonstruksis/new'


  get 'import_items/update'

  get 'import_items/destroy'
  
  
  resources :price_analysis do
  get :get_price, on: :collection
end

  resources :pipingpipes do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_pip'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
      collection do
    end
    get :import, on: :collection
  end

  resources :pipingfitings do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_fit'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :pipinggasket do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_gasket'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :pipingbolts do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_bolts'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :pipingvalves do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_valves'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :pipingspitems do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_spitems'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end
  resources :piping_flanges do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_flanges'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :civilmaterials do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_civilmaterial'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :civiljasas do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_civiljasa'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :elektrikals do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_elektrikal'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end


  resources :mechanicals do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_mechanical'
         get 'items_show/:id' => :items_show, as: 'items_show'
         delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :instrument_fields do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_instrumen_field'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :instrument_valves do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_instrumen_valve'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :instrument_fires do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_instrumen_fire'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :instrument_materings do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_instrumen_metering'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :instrument_icsss do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_instrumen_icss'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end
  
  resources :instrument_miscellaneouss do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_instrumen_miscellaneous'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :pipeline_linepipes do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_pipeline_linepipe'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end
  
  resources :pipeline_insulations do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_pipeline_insulation'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :pipeline_barreds do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_pipeline_barred'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :pipeline_valves do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_pipeline_valve'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end
    get :import, on: :collection
  end

  resources :pipeline_hot do
    get :getDataTemplate, on: :collection
    member do
        get '' => :index, as: 'index_pipeline_hot'
        get 'items_show/:id' => :items_show, as: 'items_show'
        delete 'delete_selected' => :delete_selected, as: 'delete_selected'
      end

app/controllers/piping_flanges_controller.rb
class PipingFlangesController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  def index
    @log_activities1 = Item.left_outer_joins(:brand, :disipline, :type, :product, :vendor, :price_item)
                         .where(disipline_id: 4, document: 'flange')
                         .select('*, items.id AS iditems, vendors.name AS namevendors, disiplines.name AS namedisiplines')
                         .order("price_items.date DESC")
                          respond_to do |format|
                            format.html
                            format.json {render json: ItemsIndex.new(view_context)}
    end
  end
  def getDataTemplate
    send_file 'lib/templatesDataItems/TemplateDHS/PIPING/FLANGE.xlsx', :type => "application/xlsx", :x_sendfile => true
  end
  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end
  
  def items_show
    @items = Item.left_outer_joins(:brand,:disipline,:type,:product,:vendor).where('items.id = ?', params[:id]).select("*, items.id AS iditems, vendors.name AS namevendors, disiplines.name AS namedisiplines").order('brands.name_brand ASC')
    @priceItems = PriceItem.left_outer_joins(:vendor,:currency).where(item_id: params[:id]).select('*, vendors.name AS namevendors, price_items.id AS idpriceitems')
    @vendorPrice = PriceItem.left_outer_joins(:vendor,:currency,:country).where(item_id: params[:id]).select('*, vendors.name AS namevendors, price_items.id AS idpriceitems').order('price_items.date DESC').limit(1)
    @itemss = DetailItem.left_outer_joins(:unit).where(item_id: params[:id]).select('*').order('units.unit_name DESC').limit(1)
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to index_flanges_piping_flange_path(4) , notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def delete_selected
    selected_items = params[:selected_items]
    selected_items.each do |item_id|
      item = Item.find(item_id)
      item.destroy
    end
    redirect_to index_flanges_piping_flange_path(4), notice: "Selected items have been deleted."
  end
  private

  def set_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:date,:project_name,:delivery_time,:incoterm,:vat,:term_payment,:price,:currency_id, :vendor_id, :country_id, :unit_id, :product_id, :type_id, :brand_id, :disipline_id, :size, :class_item, :dimension, :general_spec, :scope_of_supply, :others, :note, :delivery_point, :schedule, :degree, :wall_thickness, :remark, :valve_specification, :actuator_specification, :solenoid_specification, :limit_swict_specification, :sensor, :housing_spec, :flowmeter_specification, :transmitter, :process_control_system_spec_2, :safety_instrumented_system_spec, :fire_and_gas_system_spec, :remote, :termina_unit_spec, :design_code, :material_ff_construction, :date2, :sch, :document)
  end
  
  def sort_column
    columns = %w[name_brand namedisiplines name_type product_name size class_item dimension general_spec]
    columns[params[:iSortCol_0].to_i]
  end

  def sort_direction
    params[:sSortDir_0] = "desc" ? "desc" : "asc"
  end
end

app/helpers/piping_flanges_helper.rb
module PipingFlangesHelper
end

app/views/piping_flanges/_form.html.erb
    <div class="item-title2">
      <div class="card">
		        	<p class="id">Form</p>
      </div>
		</div>
    <%= form_for(@item, html: {role: "form"}) do |f| %>
                            
        <% if @item.errors.any? %>
            <div class="alert alert-danger alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span><span class="sr-only">Close
                    </span>
                </button>
                <h4>
                    <%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:
                </h4>
                    <ul>
                        <% @item.errors.full_messages.each do |msg| %>
                            <li>
                                <%= msg %>
                            </li>
                                <% end %>
                    </ul>
            </div>
        <% end %>

        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label class="control-label">Brand
                                <%= link_to new_modalbox_brands_path, class: 'btn btn-default txt-color-green', remote: true do %>
                                    <i class="fa fa-plus fa-lg"></i>
                                <% end %>
                            </label>
                            <%= f.collection_select :brand_id, Brand.order(:name_brand), :id, :name_brand, {prompt: "Select a Brand"}, {:class => 'custom-select'} %>
                        </div>
                        <div class="col">
                            <label class="control-label">
                                <span style="color:red;">
                                    *
                                </span>
                                    Vendor
                                <%= link_to new_modalbox_vendors_path, class: 'btn btn-default txt-color-green', remote: true do %>
                                    <i class="fa fa-plus fa-lg"></i>
                                <% end %>
                            </label>
                            <%= f.collection_select :vendor_id, Vendor.order(:name), :id, :name, {prompt: "Select a Vendor"}, {:class => 'custom-select', required: true} %>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label class="control-label">Disiplin
                                <%= link_to new_modalbox_disiplines_path, class: 'btn btn-default txt-color-green', remote: true do %>
                                    <i class="fa fa-plus fa-lg"></i>
                                <% end %>
                            </label>
                                <%= f.collection_select :disipline_id, Disipline.order(:name), :id, :name, {prompt: "Select a Disipline"}, {:class => 'custom-select'} %>
                        </div>
                        <div class="col">
                            <label class="control-label">Type
                                <%= link_to new_modalbox_types_path, class: 'btn btn-default txt-color-green', remote: true do %>
                                    <i class="fa fa-plus fa-lg"></i>
                                <% end %>
                            </label>
                            <%= f.collection_select :type_id, Type.order(:name_type), :id, :name_type, {prompt: "Select a Type"}, {:class => 'custom-select'} %>    
                            <!-- <%= f.collection_select :type_id, Type.select("distinct name_type"), :id, :name_type, {prompt: "Select a Type"}, {:class => 'custom-select', required: true} %>-->
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label class="control-label"><span style="color:red;">*</span>Product
                                <%= link_to new_modalbox_products_path, class: 'btn btn-default txt-color-green', remote: true do %>
                                    <i class="fa fa-plus fa-lg"></i>
                                <% end %>
                            </label>
                                <%= f.collection_select :product_id, Product.order(:product_name), :id, :product_name, {prompt: "Select a Product"}, {:class => 'custom-select', required: true} %>
                        </div>
                        <div class="col">
                            <label class="control-label">Unit
                                <%= link_to new_modalbox_units_path, class: 'btn btn-default txt-color-green', remote: true do %>
                                    <i class="fa fa-plus fa-lg"></i>
                                <% end %>
                            </label>
                                <%= f.collection_select :unit_id, Unit.order(:unit_name), :id, :unit_name, {prompt: "Select a Unit"}, {:class => 'custom-select'} %>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label class="control-label">
                                Class Item
                            </label>
                                <%= f.text_field :class_item, class: "form-control" %>
                        </div>
                        <div class="col">
                            <label class="control-label">
                                Size
                            </label>
                                <%= f.text_field :size, class: "form-control" %>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label class="control-label">
                                Schedule
                            </label>
                                <%= f.text_field :schedule, class: "form-control" %>
                        </div>
                        <div class="col">
                            <label class="control-label">
                                No Quotation
                            </label>
                                <%= f.text_field :no_quotation, class: "form-control" %>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label class="control-label">
                                <span style="color:red;">
                                    *
                                </span>
                                    General Spec
                            </label>
                                <%= f.text_area :general_spec, class: "form-control", rows: 8, required: true %>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <label class="control-label">
                                Note
                            </label>
                                <%= f.text_area :note, class: "form-control", rows: 8 %>
                        </div>
                    </div>
                </div>
                <%= f.hidden_field :document, class: "form-control", rows: 8, value: "Pipe" %>
                <div class="form-group">
                    <div class="row">
                        <div class="col">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-eye">
                                </i>
                                    Validate
                            </button>
                        </div>
                        <div class="col">
                            <%= link_to :back, style: "float: right;", class: 'btn btn-primary' do %>
                                <span class="glyphicon glyphicon-list-alt"></span>
                                Back
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            
    <% end %>

app/views/piping_flanges/edit.html.erb
<div class="header-title">
	<nav class="navba navbar-light bg-white">
		<div class="item-title">
			<p class="id">Update Piping - Flange</p>
		</div>
	</nav>
</div>
<div class="button-card">
	<section class="home-section2">   
            <%= render 'form' %>
            <%= render 'layouts/modal' %>
	</section>
</div>

app/views/piping_flanges/items_show.html.erb
<div class="header-title">
	<nav class="navba navbar-light bg-white">
		<div class="item-title">
			<p class="id">Show Item Piping - Flange</p>
		</div>
	</nav>
</div>
		<div class="tabs">
			<div class="tab-header">
				<div class="active">
					<i class="fas fa-info-circle"></i> Detail
				</div>
				<div>
					<i class="fas fa-chart-bar"></i>Price History
				</div>
			</div>
				<div class="tab-indicator">
				</div>
					<div class="tab-body">
						<div class="active">
							<h2>Detail</h2>
							<hr/>
								<table class="table table-bordered">
									<tbody>
										<tr>
											<td>Product : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @items.first.product_name.to_s %></button></td>
											<td>Type : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @items.first.name_type.to_s %></button></td>
											<td>Brand : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @items.first.name_brand.to_s %></button></td>
											<td>Size : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @items.first.size.to_s %></button></td>
											
										</tr>
										<tr>
											<td>COO : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @vendorPrice.first.country_name.to_s %></button></td>
											<td>Class Items : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @items.first.class.to_s %></button></td>
											<td>Unit : </td>
											<td>
                                                <% if @itemss.first %>
                                                    <button type="button" class="btn btn-outline-primary"><%= @itemss.first.unit_name.to_s %></button>
                                                <% else %>
                                                    <button type="button" class="btn btn-outline-primary"></button>
                                                <% end %>
                                            </td>
											
										</tr>
										<tr>
											<td>Delivery Point : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @items.first.delivery_point.to_s %></button></td>
											<td>Delivery Time : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @items.first.delivery_time.to_s %></button></td>
											<td>Incoterm : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @items.first.incoterm.to_s %></button></td>
										</tr>
                                        <tr>
											<td>Schedule : </td>
											<td><button type="button" class="btn btn-outline-primary"><%= @items.first.schedule.to_s %></button></td>

										<tr>
											<td>General Spec : </td>
											<td colspan="3"><button type="button" class="btn btn-outline-primary"><%= @items.first.general_spec.to_s %></button></td></td>
											<td>Note : </td>
											<td colspan="3"><button type="button" class="btn btn-outline-primary"><%= @items.first.note.to_s %></button></td></td>
										</tr>
										
									</tbody>
								</table>
						</div>
						<div>
							<h2>Price History</h2>
							<hr/>
								
										<%= link_to new2_price_items_path(@items.first.iditems.to_i), class: 'btn btn-primary' do %>
											<span class="glyphicon glyphicon-plus"></span>
											New Price item
										<% end %>
										<hr/>
										<table id="example" class="table table-striped table-bordered table-hover table-borderless" style="width:100%">
											<thead>
												<tr>
													<th>Vendor</th>
													<th>Price</th>
													<th>Incoterm</th>
													<th>Date</th>
													<th>Vat</th>
													<th>Note</th>
													<th></th>
													<th></th>
													<th></th>
												</tr>
											</thead>
											<tbody>
												
												<%= content_tag_for(:tr, @vendorPrice) do |price_item| %>
													
													<td>
														<%= link_to detail_modalbox_vendors_path(price_item.vendor_id), remote: true do %>
															<%= price_item.namevendors %>
														<% end %>
													</td>
													<td><%= number_to_currency(price_item.price, :unit => "#{price_item.current_name} ") %></td>
													<td><%= price_item.incoterm %></td>
													<td><%= price_item.date %></td>
													<td><%= price_item.vat %></td>
													<td><%= price_item.note %></td>
													<td><%= link_to '', price_item_path(price_item.idpriceitems), class: 'fa fa-eye btn btn-sm btn-success', title: "Detail" %></td>
													<td><%= link_to '', edit_price_item_path(price_item.idpriceitems), class: 'fas fa-pencil-alt btn btn-sm btn-warning', title: "Edit" %></td>
													<td><%= link_to '', price_item_path(price_item.idpriceitems), method: :delete, data: {confirm: 'Are you sure?'}, class: 'fa fa-trash btn btn-sm btn-danger', title: "Delete" %></td>
												
												<% end %>
												
											</tbody>
											<tfoot>
												<tr>
													<th>Vendor</th>
													<th>Price</th>
													<th>Incoterm</th>
													<th>Date</th>
													<th>Vat</th>
													<th>Note</th>
													<th></th>
													<th></th>
													<th></th>
												</tr>
											</tfoot>
										</table>
									
							
						</div>
					</div>
		</div>


	<script>
		let tabHeader = document.getElementsByClassName("tab-header")[0];
		let tabIndicator = document.getElementsByClassName("tab-indicator")[0];
		let tabBody = document.getElementsByClassName("tab-body")[0];

		let tabsPane = tabHeader.getElementsByTagName("div");

		for(let i=0;i<tabsPane.length;i++){
			tabsPane[i].addEventListener("click",function(){
				tabHeader.getElementsByClassName("active")[0].classList.remove("active");
				tabsPane[i].classList.add("active");
				tabBody.getElementsByClassName("active")[0].classList.remove("active");
				tabBody.getElementsByTagName("div")[i].classList.add("active");

				tabIndicator.style.left = `calc(calc(100% / 2) * ${i})`;
			});
		}
	</script>

app/views/piping_flanges/new.html.erb
<div class="header-title">
	<nav class="navba navbar-light bg-white">
		<div class="item-title">
			<p class="id">New Piping - Flange</p>
		</div>
	</nav>
</div>
<div class="button-card">
	<section class="home-section2">   
		<%= render 'form' %>
		<%= render 'layouts/modal' %>
	</section>
</div>